<a href="https://colab.research.google.com/github/TheElmoro/Random-Codes/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
learning_rate = 0.01
temperature = 25.5
vector = [10 , 20, 30]

scaled_vector = [ learning_rate * x for x in vector ]

print (" Original vector :", vector )
print (" Scaled vector :", scaled_vector )

 Original vector : [10, 20, 30]
 Scaled vector : [0.1, 0.2, 0.3]


In [2]:
import numpy as np

scores = np. array ([95 , 88, 72])
house_features = np. array ([1500 , 3])

print (" Student scores vector :", scores )
print (" House features vector :", house_features )

 Student scores vector : [95 88 72]
 House features vector : [1500    3]


In [3]:
import numpy as np

prices = np. array ([2 , 1, 3])
quantities = np. array ([5 , 10, 2])

total_cost = np.dot(prices , quantities )
total_cost_alt = prices @ quantities

print (" Total cost :", total_cost )
print (" Total cost (alt):", total_cost_alt )

 Total cost : 26
 Total cost (alt): 26


In [4]:
import numpy as np

position = np. array ([3 , 4])
distance = np. linalg . norm ( position )

print (" Position vector :", position )
print (" Direct distance (L2 Norm ):", distance )

manhattan_distance = np. linalg . norm ( position , ord =1)
print (" Manhattan distance (L1 Norm ):",manhattan_distance )

 Position vector : [3 4]
 Direct distance (L2 Norm ): 5.0
 Manhattan distance (L1 Norm ): 7.0


In [5]:
import numpy as np

image_matrix = np. array ([
[0, 128 , 255] ,
[50 , 100 , 150] ,
[200 , 225 , 0]
])

print (" Image Matrix :\n", image_matrix )
print (" Shape of matrix :", image_matrix . shape )

 Image Matrix :
 [[  0 128 255]
 [ 50 100 150]
 [200 225   0]]
 Shape of matrix : (3, 3)


In [6]:
import numpy as np

rotation_matrix = np. array ([
[0, -1],
[1, 0]
])

point = np. array ([3 , 1])
transformed_point = rotation_matrix @ point

print (" Original point :", point )
print (" Transformed point :", transformed_point )

 Original point : [3 1]
 Transformed point : [-1  3]


In [7]:
import numpy as np

A = np. array ([
[2, 0],
[0, 1]
])
eigenvalues , eigenvectors = np. linalg .eig(A)

print (" Eigenvalues :", eigenvalues )
print (" Eigenvectors ( columns ):\n", eigenvectors )

 Eigenvalues : [2. 1.]
 Eigenvectors ( columns ):
 [[1. 0.]
 [0. 1.]]
