<a href="https://colab.research.google.com/github/TheElmoro/Random-Codes/blob/main/Linear_Algerbra2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
learning_rate = 0.01
temperature = 25.5
print(learning_rate)

0.01


In [2]:
vector = [10, 20, 30]
print(vector)

[10, 20, 30]


In [3]:
x = 2
scaled_vector = [x * i for i in vector]
print(scaled_vector)

[20, 40, 60]


In [4]:
import numpy as np
scores = np.array([95, 88, 72])

In [5]:
print(scores)

[95 88 72]


In [6]:
print(vector*scores)

[ 950 1760 2160]


In [7]:
print(np.dot(vector, scores))

4870


In [8]:
print(vector @ scores)

4870


In [9]:
np.linalg.norm(vector)

np.float64(37.416573867739416)

In [10]:
np.linalg.norm(vector, ord=1)

np.float64(60.0)

In [11]:
r_matrix = np.array([[0,-1],[1,0]])

In [12]:
point = np.array([3,1])
transformed_point= r_matrix @ point
print(transformed_point)

[-1  3]


In [13]:
A = np.array([[2,0],[0,1]])
e_val, e_vec = np.linalg.eig(A)
print("Eigenvalues:", e_val)
print("Eigenvectors", e_vec)

Eigenvalues: [2. 1.]
Eigenvectors [[1. 0.]
 [0. 1.]]


In [14]:
A_1 = np.array([[4,2,3],[3,5,5],[1,3,5]])
e_val_1, e_vec_1 = np.linalg.eig(A_1)
print("Eigenvalues:", e_val_1)
print("Eigenvectors", e_vec_1)

Eigenvalues: [10.33127472  2.35156186  1.31716342]
Eigenvectors [[-0.46694639 -0.75193817 -0.17562641]
 [-0.73034067 -0.2773299  -0.73937996]
 [-0.49856151  0.59806112  0.64997896]]
