<a href="https://colab.research.google.com/github/TheElmoro/Random-Codes/blob/main/numpy_mini_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an array of shape (4, 5) with values 0..19. Extract the last column.
2. Given arr = np.arange(10), set all odd indices to -1 (in-place).
3. Construct a 10×10 multiplication table using broadcasting.
4. Generate 1000 samples from N(0,1), compute mean and std, and compare with theory.
5. Solve A x = b for a random 4×4 A and random b. Verify the residual is ~0.

In [ ]:
import numpy as np

M = np.arange(20).reshape((4, 5))
last_col = M[:, 4]
print("1) last column:", last_col)

arr = np.arange(10)
mask_odd = (np.arange(10) % 2 == 1)
arr[mask_odd] = -1
print("2) odds set to -1:", arr)

r = np.arange(1, 11)[:, np.newaxis]
c = np.arange(1, 11)
mul_table = r * c
print("3) multiplication table (first 5x5):")
print(mul_table[:5, :5])

samples = np.random.randn(1000)
mean_val = samples.mean()
std_val  = samples.std()
print("4) mean:", mean_val, "std:", std_val, "| theory: mean=0, std=1")

A = np.random.randn(4, 4)
b = np.random.randn(4)
x = np.linalg.solve(A, b)
residual = A @ x - b
print("5) residual norm:", np.linalg.norm(residual))


1) last column: [ 4  9 14 19]
2) odds set to -1: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
3) multiplication table (first 5x5):
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
4) mean: -0.003076781397993999 std: 1.0204301396133606 | theory: mean=0, std=1
5) residual norm: 7.696856831808123e-16
